# IMPORTANT: You must have the REST client extension installed to send these requests
# Note: You can replace any credentials here with anything else

# Register a new user
POST http://127.0.0.1:8000/api/register
Content-Type: application/json

{
    "username": "TestBee",
    "email": "TestBee@example.com",
    "password": "TestPassword"
}

###

# Login with the registered user
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "username": "TestBee",
    "password": "TestPassword"
}

###

# Logout the user
# Note: Replace the token with the one received from the login response
POST http://127.0.0.1:8000/api/logout
Authorization: Token INSERT_TOKEN_HERE

###

# Get all posts in reverse chronological order
GET http://127.0.0.1:8000/api/posts

###

# Add a post
# Note: Replace the token with the one received from the login response
POST http://127.0.0.1:8000/api/posts
Content-Type: application/json
Authorization: Token INSERT_TOKEN_HERE

{
    "title": "Post 1",
    "contents": "This is Post 1's contents"
}

###

# Get a singular post#
GET http://127.0.0.1:8000/api/posts/1

###

# Add a comment to a post
# Note: Replace the token with the one received from the login response
POST http://127.0.0.1:8000/api/posts/1
Content-Type: application/json
Authorization: Token INSERT_TOKEN_HERE

{
    "contents": "This is a comment"
}