# Generated by Django 5.0.7 on 2024-08-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posed',
            new_name='date_posted',
        ),
        migrations.AlterField(
            model_name='post',
            name='tone',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
