# Generated by Django 5.0.7 on 2024-08-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_comment_date_posted_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contents',
            field=models.TextField(),
        ),
    ]
